apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:6.0
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
      - containerPort: 27017
        protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc