apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html   
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
  - name: nginx-data
    gcePersistentDisk:
      pdName: nginx
      fsType: ext4